name: Snakemake linting

on: [pull_request]

jobs:
  setup:
    name: ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: 'test_data'
          snakefile: 'Snakefile-reprocess'
          args: >
            '--lint -c1 --config
            accession=E-MTAB-1234
            goal="reprocess"
            tool=tool
            metadata_summary=metadata_summary.yml
            bioentities_properties=bioentities_properties
            skip_steps_file=skip_steps_file
            methods_base=methods_base
            methods_dif=methods_dif
            atlas_exps=atlas_exps
            zooma_exclusions=zooma_exclusions
            isl_dir=../test_data
            isl_genomes=isl_genomes
            irap_versions=irap_versions
            irap_container=irap_container
            tmp_dir=tmp_dir
            atlas_meta_config=atlas_meta_config
            oracle_home=oracle_home
            python_user=python_user
            python_connect_string=python_connect_string
            python_password=python_password'
